"""Added email confirmation to users

Revision ID: b84bb0bda0fb
Revises: e19807d7a4a1
Create Date: 2020-11-04 21:53:48.534957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84bb0bda0fb'
down_revision = 'e19807d7a4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('registered_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_on')
    op.drop_column('users', 'email_confirmed_on')
    op.drop_column('users', 'email_confirmed')
    op.drop_column('users', 'email_confirmation_sent_on')
    # ### end Alembic commands ###
